name: First Workflows
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hello World"
            echo "Executing commands"
            echo "`date`"
      - name: Print GoodBye
        run: echo "Done - Bye"
